compiler: gcc
language: c
install:
    - sudo apt-get update
    - sudo apt-get install -y libopenal-dev libsdl2-dev libsdl2-image-dev libgles2-mesa-dev libegl1-mesa-dev astyle
script:
    - make
    - ( exit $(make fmt | grep Formatted | wc -l) )
